### ISSUE TITLE
This widget does not work on the cloud

### ISSUE THREAD

**Issue by ndelord** [chadevans/TimeCircles#1]
Although it works locally...

I get the following error: 
mendix.sys.Data.get: error in handler for 34058472181989378: Counter_widget_Counter_0.applyContext: Error: Counter_widget_Counter_0.applyContext: TypeError: jqueryTcNode.TimeCircles is not a function 

I removed some widgets that also use jQuery in order to avoid conflict but it still does not work.
Not sure though if I removed all the widgets...

**Comment by ndelord** [comment]
Here is the full stack trace:

mendix.sys.Data.get: error in handler for 34058472181989378: Counter_widget_Counter_0.applyContext: Error: Counter_widget_Counter_0.applyContext: TypeError: jqueryTcNode.TimeCircles is not a function (anonymous function) @ mxui.js?635925604622156910:29
error @ mxui.js?635925604622156910:29
(anonymous function) @ mxui.js?635925604622156910:29
window.mx.server.request.options.callback @ mxui.js?635925604622156910:29
_1aad @ mxui.js?635925604622156910:29
_1abb.handle @ mxui.js?635925604622156910:29
(anonymous function) @ mxui.js?635925604622156910:21
_2d3 @ mxui.js?635925604622156910:21
_2d1 @ mxui.js?635925604622156910:21
resolve.callback @ mxui.js?635925604622156910:21
_2d3 @ mxui.js?635925604622156910:21
_2d1 @ mxui.js?635925604622156910:21
resolve.callback @ mxui.js?635925604622156910:21
(anonymous function) @ mxui.js?635925604622156910:21
_2f8 @ mxui.js?635925604622156910:21
_2f2 @ mxui.js?635925604622156910:21
resolve @ mxui.js?635925604622156910:21
_2fe @ mxui.js?635925604622156910:21
_2f8 @ mxui.js?635925604622156910:21
_2f2 @ mxui.js?635925604622156910:21
resolve @ mxui.js?635925604622156910:21
_2fe @ mxui.js?635925604622156910:21
_2f8 @ mxui.js?635925604622156910:21
_2f2 @ mxui.js?635925604622156910:21
resolve @ mxui.js?635925604622156910:21
_2fe @ mxui.js?635925604622156910:21
_2f8 @ mxui.js?635925604622156910:21
_2f2 @ mxui.js?635925604622156910:21
resolve @ mxui.js?635925604622156910:21
_500 @ mxui.js?635925604622156910:21
_50c @ mxui.js?635925604622156910:21

**Comment by simo101** [comment]
Hi @ndelord which version of the modeller is this in? From the look of the code it seems that this issue was actually solved. But as mentioned by Jelte something else might be overriding jquery. Could you list what other widgets you have in your repository or create a blank test project with only timecircles in to make sure that it is definitely timecircles widget.

**Comment by JelteMX** [comment]
Can you check whether or not this fix will work:

https://github.com/JelteMX/Counter/raw/master/test/widgets/Counter.mpk

I [have made a fork](https://github.com/JelteMX/Counter/), so if this fixes the issue I'll create a pull request for this repo. The fix is in cf4a0a9 and is a similar thing we did in our Lightbox widget

**Comment by ndelord** [comment]
Hi Jelte, I just deployed it on my cloud and it works now!
It add a great value to my app. Thanks a lot!!!

**Comment by JelteMX** [comment]
Can you close this issue? As we have taken over the widget repository (@chadevansMX no longer works for Mendix) over [here](https://github.com/mendix/Counter), we have fixed the issue in [v2.1.0](https://github.com/mendix/Counter/releases/tag/v2.1.0) and will update this shortly in the AppStore

**Comment by ndelord** [comment]
Closed
